# Generated by Django 5.2 on 2026-03-14 05:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'ง่าย'), ('medium', 'ปานกลาง'), ('hard', 'ยาก')], default='medium', max_length=10, verbose_name='ระดับความยาก')),
                ('body_th', models.TextField(verbose_name='โจทย์ (ไทย)')),
                ('body_en', models.TextField(blank=True, verbose_name='โจทย์ (อังกฤษ)')),
                ('body_latex', models.TextField(blank=True, verbose_name='สูตร LaTeX')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/%Y/%m/', verbose_name='รูปภาพประกอบ')),
                ('explanation_th', models.TextField(blank=True, verbose_name='เฉลย/อธิบาย (ไทย)')),
                ('explanation_en', models.TextField(blank=True, verbose_name='เฉลย/อธิบาย (อังกฤษ)')),
                ('explanation_latex', models.TextField(blank=True, verbose_name='สูตร LaTeX เฉลย')),
                ('explanation_image', models.ImageField(blank=True, null=True, upload_to='questions/explanations/%Y/%m/', verbose_name='รูปภาพประกอบเฉลย')),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='คะแนนเต็ม')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='แท็ก')),
                ('source', models.CharField(blank=True, help_text='เช่น PAT1 2566, สอบกลางภาค 1/2567', max_length=200, verbose_name='แหล่งที่มา')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='subjects.subject', verbose_name='วิชา')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='subjects.topic', verbose_name='หัวข้อ')),
            ],
            options={
                'verbose_name': 'ข้อสอบ',
                'verbose_name_plural': 'ข้อสอบ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EssayQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.question')),
                ('sample_answer', models.TextField(blank=True, help_text='คำตอบตัวอย่างสำหรับครูใช้ในการตรวจ', verbose_name='เฉลยตัวอย่าง')),
                ('max_words', models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนคำสูงสุด')),
                ('grading_rubric', models.TextField(blank=True, verbose_name='เกณฑ์การให้คะแนน (Rubric)')),
            ],
            options={
                'verbose_name': 'ข้อสอบอัตนัย',
                'verbose_name_plural': 'ข้อสอบอัตนัย',
            },
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='FillInBlankQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.question')),
                ('grading_mode', models.CharField(choices=[('exact', 'ตรงทุกตัวอักษร'), ('ignore_case', 'ไม่สนตัวพิมพ์เล็ก/ใหญ่'), ('contains', 'มีคำที่อยู่ในคำตอบ')], default='ignore_case', max_length=15, verbose_name='วิธีตรวจคำตอบ')),
            ],
            options={
                'verbose_name': 'ข้อสอบเติมคำ',
                'verbose_name_plural': 'ข้อสอบเติมคำ',
            },
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='MatchingQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.question')),
                ('shuffle_right', models.BooleanField(default=True, verbose_name='สุ่มลำดับคอลัมน์ขวา')),
            ],
            options={
                'verbose_name': 'ข้อสอบจับคู่',
                'verbose_name_plural': 'ข้อสอบจับคู่',
            },
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.question')),
                ('answer_mode', models.CharField(choices=[('single', 'คำตอบเดียว'), ('multiple', 'หลายคำตอบ')], default='single', max_length=10, verbose_name='รูปแบบคำตอบ')),
            ],
            options={
                'verbose_name': 'ข้อสอบปรนัย',
                'verbose_name_plural': 'ข้อสอบปรนัย',
            },
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.question')),
                ('correct_answer', models.BooleanField(help_text='True = ถูก, False = ผิด', verbose_name='คำตอบที่ถูก')),
                ('true_label', models.CharField(default='ถูก', max_length=50, verbose_name='ข้อความแทน "ถูก"')),
                ('false_label', models.CharField(default='ผิด', max_length=50, verbose_name='ข้อความแทน "ผิด"')),
            ],
            options={
                'verbose_name': 'ข้อสอบถูก/ผิด',
                'verbose_name_plural': 'ข้อสอบถูก/ผิด',
            },
            bases=('questions.question',),
        ),
        migrations.CreateModel(
            name='BlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_number', models.PositiveSmallIntegerField(help_text='ตามหมายเลขใน {{N}}', verbose_name='ช่องที่')),
                ('answer_text', models.CharField(max_length=200, verbose_name='คำตอบที่ถูก')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='ลำดับ (ถ้ามีหลายคำตอบ)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_answers', to='questions.fillinblankquestion', verbose_name='ข้อสอบ')),
            ],
            options={
                'verbose_name': 'คำตอบช่องว่าง',
                'verbose_name_plural': 'คำตอบช่องว่าง',
                'ordering': ['blank_number', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_body', models.TextField(verbose_name='คอลัมน์ซ้าย (ถาม)')),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='questions/matching/%Y/%m/', verbose_name='รูปภาพคอลัมน์ซ้าย')),
                ('right_body', models.TextField(verbose_name='คอลัมน์ขวา (ตอบ)')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='questions/matching/%Y/%m/', verbose_name='รูปภาพคอลัมน์ขวา')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='ลำดับ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='questions.matchingquestion', verbose_name='ข้อสอบ')),
            ],
            options={
                'verbose_name': 'คู่จับคู่',
                'verbose_name_plural': 'คู่จับคู่',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5, verbose_name='ตัวอักษร (A, B, C, D)')),
                ('body_th', models.TextField(verbose_name='ตัวเลือก (ไทย)')),
                ('body_en', models.TextField(blank=True, verbose_name='ตัวเลือก (อังกฤษ)')),
                ('body_latex', models.TextField(blank=True, verbose_name='LaTeX')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/choices/%Y/%m/', verbose_name='รูปภาพ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='เป็นคำตอบที่ถูก')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='ลำดับ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.multiplechoicequestion', verbose_name='ข้อสอบ')),
            ],
            options={
                'verbose_name': 'ตัวเลือก',
                'verbose_name_plural': 'ตัวเลือก',
                'ordering': ['order_index', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'difficulty'], name='questions_q_subject_384fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'topic'], name='questions_q_subject_c4fa34_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'created_at'], name='questions_q_is_acti_c7def7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'label')},
        ),
    ]
