# Generated by Django 5.2 on 2026-03-14 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=200, verbose_name='ชื่อวิชา (ไทย)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='ชื่อวิชา (อังกฤษ)')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='รหัสวิชา')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('color', models.CharField(default='#4F86C6', max_length=7, verbose_name='สี (Hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
            ],
            options={
                'verbose_name': 'วิชา',
                'verbose_name_plural': 'วิชา',
                'ordering': ['name_th'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=200, verbose_name='ชื่อหัวข้อ (ไทย)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='ชื่อหัวข้อ (อังกฤษ)')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='ลำดับ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='subjects.topic', verbose_name='หัวข้อแม่')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.subject', verbose_name='วิชา')),
            ],
            options={
                'verbose_name': 'หัวข้อ',
                'verbose_name_plural': 'หัวข้อ',
                'ordering': ['subject', 'order_index', 'name_th'],
                'unique_together': {('subject', 'parent', 'name_th')},
            },
        ),
    ]
