# Generated by Django 5.2 on 2026-03-14 05:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_th', models.CharField(max_length=300, verbose_name='ชื่อชุดข้อสอบ (ไทย)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='ชื่อชุดข้อสอบ (อังกฤษ)')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('time_limit_min', models.PositiveIntegerField(blank=True, help_text='ว่างไว้ = ไม่จำกัดเวลา', null=True, verbose_name='เวลาจำกัด (นาที)')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='คะแนนเต็มรวม')),
                ('pass_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='คะแนนผ่าน')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='สุ่มลำดับข้อสอบ')),
                ('shuffle_choices', models.BooleanField(default=False, verbose_name='สุ่มลำดับตัวเลือก')),
                ('show_result', models.CharField(choices=[('immediately', 'แสดงทันทีหลังตอบแต่ละข้อ'), ('after_submit', 'แสดงหลังส่งข้อสอบ'), ('manual', 'ครูเปิดเผยเอง'), ('never', 'ไม่แสดง')], default='after_submit', max_length=20, verbose_name='การแสดงผลลัพธ์')),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='ว่างไว้ = ไม่จำกัด', null=True, verbose_name='จำนวนครั้งที่สอบได้')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='เริ่มสอบ')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='สิ้นสุด')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('published', 'เผยแพร่'), ('archived', 'เก็บถาวร')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='subjects.subject', verbose_name='วิชา')),
            ],
            options={
                'verbose_name': 'ชุดข้อสอบ',
                'verbose_name_plural': 'ชุดข้อสอบ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='ลำดับ')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='ว่างไว้ = ใช้คะแนนจากข้อสอบต้นฉบับ', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='คะแนน (override)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam', verbose_name='ชุดข้อสอบ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='questions.question', verbose_name='ข้อสอบ')),
            ],
            options={
                'verbose_name': 'ข้อสอบในชุด',
                'verbose_name_plural': 'ข้อสอบในชุด',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, verbose_name='ครั้งที่')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='เริ่มสอบ')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='ส่งข้อสอบ')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='หมดเวลา')),
                ('status', models.CharField(choices=[('in_progress', 'กำลังทำข้อสอบ'), ('submitted', 'ส่งแล้ว'), ('expired', 'หมดเวลา'), ('graded', 'ตรวจแล้ว')], default='in_progress', max_length=20, verbose_name='สถานะ')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='คะแนนรวมที่ได้')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='ผ่าน/ไม่ผ่าน')),
                ('question_order', models.JSONField(default=list, verbose_name='ลำดับข้อสอบ (snapshot)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exam', verbose_name='ชุดข้อสอบ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สอบ')),
            ],
            options={
                'verbose_name': 'การสอบ',
                'verbose_name_plural': 'การสอบ',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='คำตอบข้อความ (อัตนัย/เติมคำ)')),
                ('answer_boolean', models.BooleanField(blank=True, null=True, verbose_name='คำตอบถูก/ผิด')),
                ('answer_matching', models.JSONField(blank=True, null=True, verbose_name='คำตอบจับคู่')),
                ('is_correct', models.BooleanField(blank=True, help_text='None = ยังไม่ตรวจ (อัตนัย)', null=True, verbose_name='ถูกต้อง')),
                ('score_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='คะแนนที่ได้')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='วันที่ตรวจ')),
                ('feedback', models.TextField(blank=True, verbose_name='ความเห็นของครู')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='ตอบเมื่อ')),
                ('answer_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.choice', verbose_name='ตัวเลือกที่เลือก (ปรนัย)')),
                ('answer_choices', models.ManyToManyField(blank=True, related_name='answers_multiple', to='questions.choice', verbose_name='ตัวเลือกที่เลือก (ปรนัยหลายคำตอบ)')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL, verbose_name='ตรวจโดย')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question', verbose_name='ข้อสอบ')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsession', verbose_name='การสอบ')),
            ],
            options={
                'verbose_name': 'คำตอบ',
                'verbose_name_plural': 'คำตอบ',
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status', 'starts_at'], name='exams_exam_status_9d48dc_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject', 'status'], name='exams_exam_subject_c655e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('exam', 'question')},
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam', 'user'], name='exams_exams_exam_id_41f94a_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status', 'started_at'], name='exams_exams_status_9f3d25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('exam', 'user', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['session', 'question'], name='exams_exama_session_45205a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('session', 'question')},
        ),
    ]
